### ISSUE TITLE
New line in scanning results with -title flag

### ISSUE THREAD

**Issue by m-1tZ** [projectdiscovery/httpx#433]
### httpx version:
latest version, which means v1.1.3

### Current Behavior:
Some website titles inherit a newline character. Scanning with the `-title` does split a scanning result into two separate lines even though it should be in one. Example:
https://x.x.com [LONG HEADER
– Some more Header] [cloudflare] [vhost] [Cloudflare,Google Tag Manager,Shopify,Typekit]

### Expected Behavior:
I expected this to be in one line like:
https://x.x.com [LONG HEADER – Some more Header] [cloudflare] [vhost] [Cloudflare,Google Tag Manager,Shopify,Typekit]

### Steps To Reproduce:
1. `echo "https://sneakers.tomorrowland.com" | httpx -no-color -random-agent -title -cdn -web-server -vhost -tech-detect -title tls-grab -mc 200 `

### Anything else:
A solution could be escaping characters in title?

**Comment by ehsandeep** [comment]
@m-1tZ this is now fixed in the dev branch, thanks for reporting.

**Comment by Leetcore** [comment]
Someone did change the string replacement and this bug is back again:

Test:

`httpx -u www.maskor.fh-aachen.de -title`

```
[INF] Current httpx version v1.3.6 (latest)
https://www.maskor.fh-aachen.de [Willkommen beim MASKOR Institut!
  —
  
  MASKOR Institut
  
  | FH Aachen UoAS]
```
